// <auto-generated />
namespace MasterData.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Dev_1001_01 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Dev_1001_01));
        
        string IMigrationMetadata.Id
        {
            get { return "201802260410104_Dev_1001_01"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
