// <auto-generated />
namespace Identity.Api.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Dev_1000 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Dev_1000));
        
        string IMigrationMetadata.Id
        {
            get { return "201802020800110_Dev_1000"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
