///////////////////////////////////////////////////////////
//  Authorization.cs
//  Implementation of the Class Authorization
//  Generated by Enterprise Architect
//  Created on:      15-Jan-2018 10:43:18 AM
//  Original author: sjafrudin.lamusu
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace FieldSupport.Domain {
	public class Authorization {

		public Authorization(){

		}

		~Authorization(){

		}

	}//end Authorization

}//end namespace FieldSupport.Domain