///////////////////////////////////////////////////////////
//  Category.cs
//  Implementation of the Class Category
//  Generated by Enterprise Architect
//  Created on:      15-Jan-2018 10:43:18 AM
//  Original author: sjafrudin.lamusu
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using FieldSupport.Domain;
namespace FieldSupport.Domain {
	public class Category {

		public FieldSupport.Domain.Ticket m_Ticket;

		public Category(){

		}

		~Category(){

		}

	}//end Category

}//end namespace FieldSupport.Domain