///////////////////////////////////////////////////////////
//  Class1.cs
//  Implementation of the Class Class1
//  Generated by Enterprise Architect
//  Created on:      15-Jan-2018 10:31:29 AM
//  Original author: sjafrudin.lamusu
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Class1 {

	public Engineer m_Engineer;
	public Category m_Category;

	public Class1(){

	}

	~Class1(){

	}

}//end Class1