///////////////////////////////////////////////////////////
//  Customer.cs
//  Implementation of the Class Customer
//  Generated by Enterprise Architect
//  Created on:      15-Jan-2018 10:43:18 AM
//  Original author: sjafrudin.lamusu
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace FieldSupport.Domain {
	public class Customer {

		public Customer(){

		}

		~Customer(){

		}

	}//end Customer

}//end namespace FieldSupport.Domain