///////////////////////////////////////////////////////////
//  Engineer.cs
//  Implementation of the Class Engineer
//  Generated by Enterprise Architect
//  Created on:      15-Jan-2018 10:43:18 AM
//  Original author: sjafrudin.lamusu
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using FieldSupport.Domain;
namespace FieldSupport.Domain {
	public class Engineer {

		public FieldSupport.Domain.Ticket m_Ticket;

		public Engineer(){

		}

		~Engineer(){

		}

	}//end Engineer

}//end namespace FieldSupport.Domain