///////////////////////////////////////////////////////////
//  Review.cs
//  Implementation of the Class Review
//  Generated by Enterprise Architect
//  Created on:      15-Jan-2018 10:43:19 AM
//  Original author: sjafrudin.lamusu
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using FieldSupport.Domain;
namespace FieldSupport.Domain {
	public class Review {

		public FieldSupport.Domain.Customer m_Customer;

		public Review(){

		}

		~Review(){

		}

	}//end Review

}//end namespace FieldSupport.Domain