///////////////////////////////////////////////////////////
//  Task.cs
//  Implementation of the Class Task
//  Generated by Enterprise Architect
//  Created on:      15-Jan-2018 10:43:19 AM
//  Original author: sjafrudin.lamusu
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using FieldSupport.Domain;
namespace FieldSupport.Domain {
	public class Task {

		public FieldSupport.Domain.Ticket m_Ticket;

		public Task(){

		}

		~Task(){

		}

	}//end Task

}//end namespace FieldSupport.Domain