///////////////////////////////////////////////////////////
//  Ticket.cs
//  Implementation of the Class Ticket
//  Generated by Enterprise Architect
//  Created on:      15-Jan-2018 10:43:19 AM
//  Original author: sjafrudin.lamusu
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using FieldSupport.Domain;
namespace FieldSupport.Domain {
	public class Ticket {

		public FieldSupport.Domain.Customer m_Customer;

		public Ticket(){

		}

		~Ticket(){

		}

	}//end Ticket

}//end namespace FieldSupport.Domain