///////////////////////////////////////////////////////////
//  Ticket Status.cs
//  Implementation of the Enumeration TicketStatus
//  Generated by Enterprise Architect
//  Created on:      15-Jan-2018 10:43:19 AM
//  Original author: sjafrudin.lamusu
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace FieldSupport.Domain {
	public enum TicketStatus : int {

	}//end TicketStatus

}//end namespace FieldSupport.Domain