// <auto-generated />
namespace FieldSupport.Api.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Dev_1000_02 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Dev_1000_02));
        
        string IMigrationMetadata.Id
        {
            get { return "201802050831430_Dev_1000_02"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
